import type { ReactElement } from "react";
import { ConcurrentRoot } from "react-reconciler/constants";

import { Tag } from "./constants";
import { HostElement } from "./host-element";
import type { Container } from "./reconciler";
import { TestReconciler } from "./reconciler";

// Refs:
// https://github.com/facebook/react/blob/main/packages/react-test-renderer/src/ReactFiberConfigTestHost.js
// https://github.com/facebook/react/blob/main/packages/react-noop-renderer/src/createReactNoop.js
// https://github.com/facebook/react/blob/main/packages/react-native-renderer/src/ReactFiberConfigFabric.js

const defaultCreateMockNode = () => ({});

const defaultOnUncaughtError = (error: unknown, errorInfo: ErrorInfo) => {
  console.error("Uncaught error:", error, errorInfo);
};
const defaultOnCaughtError = (error: unknown, errorInfo: ErrorInfo) => {
  console.error("Caught error:", error, errorInfo);
};
const defaultOnRecoverableError = (error: unknown, errorInfo: ErrorInfo) => {
  console.error("Recoverable error:", error, errorInfo);
};

/**
 * Options for configuring the test renderer root.
 */
export type RootOptions = {
  /** Types of valid text components. */
  textComponents?: string[];

  /** Function to create mock nodes for refs. */
  createNodeMock?: (element: ReactElement) => object;

  /** Callback called when React catches an error in an Error Boundary. Called with the error caught by the Error Boundary, and an errorInfo object containing the componentStack. */
  onCaughtError?: ErrorHandler;

  /** Callback called when an error is thrown and not caught by an Error Boundary. Called with the error that was thrown, and an errorInfo object containing the componentStack. */
  onUncaughtError?: ErrorHandler;

  /** Callback called when React automatically recovers from errors. Called with an error React throws, and an errorInfo object containing the componentStack. Some recoverable errors may include the original error cause as error.cause. */
  onRecoverableError?: ErrorHandler;

  /** A string prefix React uses for IDs generated by useId. Useful to avoid conflicts when using multiple roots on the same page. */
  identifierPrefix?: string;

  /** Enable React Strict Mode. */
  isStrictMode?: boolean;
};

/** Callback for handling React errors. */
export type ErrorHandler = (error: unknown, errorInfo: ErrorInfo) => void;

/** Error information provided to error handlers. */
export type ErrorInfo = {
  componentStack: string;
};

/**
 * Root instance returned by createRoot. Provides methods to render and unmount components.
 */
export type Root = {
  /** Render a React element into the root. Must be called within act(). */
  render: (element: ReactElement) => void;
  /** Unmount the root and clean up. Must be called within act(). */
  unmount: () => void;
  /** The root container element. */
  container: HostElement;
};

/**
 * Create a new test renderer root instance.
 *
 * @param options - Optional configuration for the renderer.
 * @returns A Root instance with render, unmount, and container properties.
 */
export function createRoot(options?: RootOptions): Root {
  let container: Container | null = {
    tag: Tag.Container,
    parent: null,
    children: [],
    isHidden: false,
    config: {
      textComponents: options?.textComponents,
      createNodeMock: options?.createNodeMock ?? defaultCreateMockNode,
    },
  };

  // eslint-disable-next-line @typescript-eslint/no-unsafe-assignment
  // @types/react-reconciler types don't fully match react-reconciler's actual Flow types.
  // The return type is correct at runtime but TypeScript can't verify it statically.
  // Correctness is verified through tests.
  let containerFiber = TestReconciler.createContainer(
    container,
    ConcurrentRoot,
    null, // hydrationCallbacks
    options?.isStrictMode ?? false,
    false, // concurrentUpdatesByDefaultOverride
    options?.identifierPrefix ?? "",
    options?.onUncaughtError ?? defaultOnUncaughtError,
    options?.onCaughtError ?? defaultOnCaughtError,
    // @ts-expect-error @types/react-reconciler types don't include onRecoverableError parameter
    // in the createContainer signature, but react-reconciler's actual Flow types do.
    // Correctness is verified through tests.
    options?.onRecoverableError ?? defaultOnRecoverableError,
    null, // transitionCallbacks
  );

  const render = (element: ReactElement) => {
    if (containerFiber == null) {
      throw new Error("Cannot render after unmount");
    }

    TestReconciler.updateContainer(element, containerFiber, null, null);
  };

  const unmount = () => {
    if (container == null) {
      return;
    }

    TestReconciler.updateContainer(null, containerFiber, null, null);

    containerFiber = null;
    container = null;
  };

  return {
    render,
    unmount,
    get container(): HostElement {
      if (container == null) {
        throw new Error("Cannot access .container on unmounted test renderer");
      }

      return HostElement.fromInstance(container);
    },
  };
}
